# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 802c9b3ab40bd438eba9ec7cf767282e3addc8c240faf16c9968c18a6dc8b71f35f5448e90c1407d681b9632dd24936ee4b5c50c7b04b08c658f258d3b68cc32

test:
  secret_key_base: 8d89ddd6f8857efcb3c8e19b3f1b3ef5f0808bc08215a305ed3e707f6f00c08b32f03c5475491b372c3c9111ed8c11fc7f9b385ec41aa762c3089429da402803

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
